# Generated by Django 4.0.7 on 2024-03-11 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_book', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
