# Generated by Django 4.0.7 on 2024-03-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Limitation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
