# Generated by Django 4.0.7 on 2024-03-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_limitation_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, default='action', max_length=30, null=True),
        ),
    ]
