# Generated by Django 4.0.7 on 2024-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Limitation',
            field=models.BooleanField(default=True),
        ),
    ]
