# Generated by Django 4.0.7 on 2024-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_otp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
