# Generated by Django 4.0.7 on 2024-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
