# Generated by Django 4.0.7 on 2024-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_baseuser_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='otp',
            field=models.PositiveIntegerField(default=264368),
        ),
    ]
