# Generated by Django 4.0.7 on 2024-03-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_baseuser_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='otp',
            field=models.PositiveIntegerField(default=504959),
        ),
    ]
